apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: payments-dev-appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - appName: payments
            namespace: payments-dev
            path: services/app

  template:
    metadata:
      name: '{{appName}}-dev'
    spec:
      project: payments-project

      source:
        repoURL: https://github.com/sainarendrapanga04/app-gitops.git
        targetRevision: main
        path: '{{path}}'

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
